accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import UserCreate

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", UserCreate.as_view(), name="signup"),
]

projects/urls.py
from django.urls import path

from .views import ProjectListView, ProjectDetailView, ProjectCreateView

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from .views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls"), name="accounts"),
    path("projects/", include("projects.urls"), name="projects"),
    path("tasks/", include("tasks.urls"), name="tasks"),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

accounts/models.py
# from django.db import models

projects/models.py
from django.db import models

from django.contrib.auth.models import User


# Creating a model for projects
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(User, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models

from django.contrib.auth.models import User


# Creating a model for project tasks
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
# from django.shortcuts import render

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


# Create your views here.
class UserCreate(CreateView):
    form_class = UserCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("home")

projects/views.py
# from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.shortcuts import redirect

from .models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "new.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        new = form.save(commit=False)
        new.save()
        form.save_m2m()
        return redirect("show_project", pk=new.id)

tasks/views.py
# from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

from .models import Task

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/new.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]
    success_url = reverse_lazy("list_projects")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template = "tasks/list.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <main>
        <div>
            <h1>{{ project.name}} </h1>
            {{ project.description|markdownify }}
            <h2>Tasks</h2>
            <p><a href="{% url "create_task" %}">Create a new task</a></p>
            {% if not project.tasks.all %}
                <p>This project has no tasks</p>
            {% else %}
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </tr>
                    {% for item in project.tasks.all %}
                        <tr>
                            <td>{{ item.name }}</td>
                            <td>{{ item.assignee }}</td>
                            <td>{{ item.start_date|date:"Y-m-d" }}</td>
                            <td>{{ item.due_date|date:"Y-m-d" }}</td>
                            <td>{{ item.is_completed|yesno:"Yes, No, Maybe" }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Projects</h1>
            <a href="{% url "create_project" %}">Create a new project</a>
            {% if not project_list %}
                <p>You are not assigned to any projects</p>
            {% else %}
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Number of Tasks</th>
                    </tr>
                    {% for project in project_list %}
                        <tr>
                            <td><a href="{% url "show_project" project.pk %}">{{ project.name }}</a></td>
                            <td>{{ project.tasks.all | length }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Tasks</h1>
            {% if not task_list %}
                <p>You have no tasks</p>
            {% else %}
                <table >
                    <tr>
                        <th>Name</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Is Completed</th>
                    </tr>
                    {% for each in task_list %}
                        <tr>
                            <td>{{ each.name }}</td>
                            <td>{{ each.start_date|date:"Y-m-d" }}</td>
                            <td>{{ each.due_date|date:"Y-m-d" }}</td>
                            {% if each.is_completed == True %}
                                <td>Done</td>
                            {% else %}
                                <td>
                                    <form method="post" action="{% url 'complete_task' each.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Project Tracker</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url "show_my_tasks" %}">My tasks</a></li>
                        <li><a href="{% url "list_projects" %}">My projects</a></li>
                        <li><a href="{% url "logout" %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url "login" %}">Login</a></li>
                        <li><a href="{% url "signup" %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>